@echo off
echo 🎯 Iniciando SaaS Chatbot Inteligente...

cd backend

echo 🔄 Executando migrações...
alembic upgrade head || echo ⚠️ Migrações falharam, continuando...

echo 🚀 Iniciando servidor FastAPI...
python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload